//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockTest.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MockTestDBEntities : DbContext
    {
        public MockTestDBEntities()
            : base("name=MockTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_answers> tbl_answers { get; set; }
        public DbSet<tbl_examtest_info> tbl_examtest_info { get; set; }
        public DbSet<tbl_examtest_info_detail> tbl_examtest_info_detail { get; set; }
        public DbSet<tbl_examtest_info_detail_answers> tbl_examtest_info_detail_answers { get; set; }
        public DbSet<tbl_grade_master> tbl_grade_master { get; set; }
        public DbSet<tbl_login> tbl_login { get; set; }
        public DbSet<tbl_questions> tbl_questions { get; set; }
        public DbSet<tbl_registration> tbl_registration { get; set; }
        public DbSet<tbl_role> tbl_role { get; set; }
        public DbSet<tbl_subjectCategory> tbl_subjectCategory { get; set; }
        public DbSet<tbl_subjectMaster> tbl_subjectMaster { get; set; }
        public DbSet<tbl_user_in_roles> tbl_user_in_roles { get; set; }
        public DbSet<tbl_verification_info> tbl_verification_info { get; set; }
        public DbSet<tbl_exception> tbl_exception { get; set; }
        public DbSet<tbl_ExamDetail> tbl_ExamDetail { get; set; }
    }
}
