//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subjectMaster
    {
        public tbl_subjectMaster()
        {
            this.tbl_subjectCategory = new HashSet<tbl_subjectCategory>();
        }
    
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<tbl_subjectCategory> tbl_subjectCategory { get; set; }
    }
}
