//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_examtest_info
    {
        public int ExamTestId { get; set; }
        public string ExamTestUserName { get; set; }
        public System.Guid ExamTestSessionId { get; set; }
        public System.DateTime ExamTestStartDateTime { get; set; }
        public string ExamTestForSubjectCategory { get; set; }
        public string ExamTestCompleteStatus { get; set; }
        public Nullable<System.DateTime> ExamTestEndTime { get; set; }
        public Nullable<double> TotalTimeInMinutes { get; set; }
        public int TotalNoOfQuestion { get; set; }
        public int TotalCorrectAnswer { get; set; }
        public int TotalMarks { get; set; }
        public string Grade { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tbl_login tbl_login { get; set; }
    }
}
