//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_in_roles
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tbl_login tbl_login { get; set; }
        public virtual tbl_role tbl_role { get; set; }
    }
}
