//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grade_master
    {
        public int Id { get; set; }
        public Nullable<int> StratRange { get; set; }
        public Nullable<int> EndRange { get; set; }
        public string Grade { get; set; }
    }
}
