//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExamDetail
    {
        public int Id { get; set; }
        public string EmailId { get; set; }
        public int SubjectId { get; set; }
        public int CategoryId { get; set; }
        public int TestDuration { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    }
}
