//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subjectCategory
    {
        public tbl_subjectCategory()
        {
            this.tbl_questions = new HashSet<tbl_questions>();
        }
    
        public int Id { get; set; }
        public string SubjectCategory { get; set; }
        public int SubjectId { get; set; }
    
        public virtual ICollection<tbl_questions> tbl_questions { get; set; }
        public virtual tbl_subjectMaster tbl_subjectMaster { get; set; }
    }
}
